PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wfdesc: <http://purl.org/wf4ever/wfdesc#>
PREFIX components: <http://purl.org/DP/components#>
PREFIX cc: <http://creativecommons.org/ns#>
SELECT *
WHERE {
  ?workflow a wfdesc:Workflow.
  ?workflow wfdesc:hasSubProcess ?tool.
  ?tool components:requiresInstallation ?installation.
  ?installation components:hasEnvironment ?env.
  ?env components:hasEnvironmentType components:LinuxEnvironment.
}
